### ISSUE TITLE
2 min please | I will close issue myself

### ISSUE THREAD

**Issue by graysuit** [thelinuxchoice/evilreg#4]
**Windows Defender** is using a server to deliver malicious files for scanning.
I want to **block** this server **without administrative rights.**

So sir do you have any idea ?
How I can **block an IP or URL** in windows **without administrative rights.**

Like host or firewall, it takes **administrative rights.**
Try to work on it in next repositories.

This topic is similar to Evil Reg.
Evil Reg is great idea behind it sets the startup registry and runs command.
TH3VKZ :)

**Comment by thelinuxchoice** [comment]
thanks for getting in touch, i'll think a solution

**Comment by graysuit** [comment]
My message delivered,
So I am now closing issue.
:)
